import { useState } from 'react'
import { motion } from 'framer-motion'
import { ChevronDown } from 'lucide-react'
import type { RunStatus, SearchPlanView } from '../types'

const INTENT_LABEL: Record<string, string> = {
  adjacent_portfolio: 'Adjacent portfolio',
  thesis_signal: 'Thesis signal',
  fund_activity: 'Fund activity',
  geo_crossing: 'Geography crossing',
  portfolio_gap: 'Portfolio gap',
  recent_exit: 'Recent exit',
}

export function PlanView({ plan, run }: { plan: SearchPlanView | null; run: RunStatus | null }) {
  const [expanded, setExpanded] = useState<string | null>(null)
  const totalQueries = plan?.intents.reduce((sum, intent) => sum + intent.queries.length, 0) ?? 0

  return (
    <section className="flex min-w-0 flex-1 flex-col overflow-y-auto" aria-label="Search plan">
      <div className="px-5 pb-3 pt-4">
        <h2 className="font-display text-[22px] font-bold leading-tight tracking-tight text-bright">
          Search plan — {totalQueries} queries
        </h2>
        <p className="mt-0.5 text-[12px] text-mute">
          One profile expands into {plan?.intents.length ?? 0} intents and several hundred narrow queries, fired
          concurrently. Plan generated by {plan?.generated_by ?? '—'}.
        </p>
      </div>

      {run && (
        <div className="mx-5 mb-3 grid gap-2 rounded-md border border-line bg-surface p-3 sm:grid-cols-4">
          {[
            ['wall clock', `${run.retrieval_stats.wall_time_ms}ms`],
            ['p50 latency', `${run.retrieval_stats.p50_latency_ms}ms`],
            ['peak concurrency', String(run.retrieval_stats.max_concurrency)],
            ['results', run.retrieval_stats.results.toLocaleString()],
          ].map(([label, value]) => (
            <div key={label}>
              <p className="label-mono text-mute">{label}</p>
              <p className="mt-0.5 font-mono text-[15px] font-bold text-lime">{value}</p>
            </div>
          ))}
        </div>
      )}

      <div className="space-y-1.5 px-5 pb-5">
        {plan?.intents.map((intent) => {
          const open = expanded === intent.id
          return (
            <div key={intent.id} className="overflow-hidden rounded-md border border-line bg-surface">
              <button
                type="button"
                onClick={() => setExpanded(open ? null : intent.id)}
                aria-expanded={open}
                className="flex w-full items-center gap-3 px-3 py-2.5 text-left transition-colors hover:bg-raised"
              >
                <ChevronDown
                  size={13}
                  className={`shrink-0 text-mute transition-transform ${open ? 'rotate-180' : ''}`}
                  aria-hidden
                />
                <span className="min-w-0 flex-1">
                  <span className="block font-display text-[13px] font-semibold text-bright">
                    {INTENT_LABEL[intent.kind] ?? intent.kind}
                  </span>
                  <span className="block truncate text-[11px] text-mute">{intent.rationale}</span>
                </span>
                <span className="shrink-0 rounded bg-raised px-1.5 py-0.5 font-mono text-[10px] text-body">
                  {intent.queries.length} queries
                </span>
              </button>

              {open && (
                <motion.ul
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: 'auto', opacity: 1 }}
                  className="max-h-56 overflow-y-auto border-t border-line-soft bg-ink px-3 py-2 font-mono text-[10px] leading-relaxed text-mute"
                >
                  {intent.queries.map((query) => (
                    <li key={query} className="truncate">
                      <span className="text-lime/60">›</span> {query}
                    </li>
                  ))}
                </motion.ul>
              )}
            </div>
          )
        })}
        {!plan && <p className="font-mono text-[11px] text-mute">Run a live search to generate a plan.</p>}
      </div>
    </section>
  )
}
